version: "3.9"
services:
  heysteimkebase:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "30000:443"
    volumes:
      - "datahsbs:/opt/rlserv/build/data:rw"
volumes:
  datahsbs: